### ISSUE TITLE
Разделение докерфайла на два

### ISSUE THREAD

**Issue by nixel2007** [Infactum/onec_dock#2]
Выделил у себя base-образ с 1сными зависимостями и собственно сборку образа с 1ской, которая наследуется от базового образа.

Было бы интересно такое видеть в этом репе в виде пулл-реквеста, или моно-докерфайл - осознанное решение?

**Comment by Infactum** [comment]
А какое применение образа с зависимостями?
Если задача ускорить сборку контейнеров с разными версиями, то достаточно выделить зависимости в отдельной слой (отдельная команда RUN). Против этого ничего не имею.

**Comment by nixel2007** [comment]
да, сборка контейнеров с разными версиями. плюс последующее быстрое обновление образов с 1с при обновлении "базового образа".

В целом разделение RUN скорее всего решит эту задачу. остается проблема требования сборки на той же машине. попробую теперь собрать обратно)

**Comment by nixel2007** [comment]
Тогда в догонку вопрос - зачем эти пляски с nginx (который, к слову, я так и не смог запустить под виндой)?

Та же задача решается перемещением dist внутрь thick_client и добавлением `COPY dist/ .` в докерфайл. в чем сакральный смысл?

**Comment by Infactum** [comment]
Чтобы не иметь слой с дистрибутивами, который будет создан во время COPY

**Comment by Infactum** [comment]
Закрыто https://github.com/Infactum/onec_dock/pull/3
