### ISSUE TITLE
Скрипт "download.sh" выполняется, но ничего не скачивает

### ISSUE THREAD

**Issue by Synoecium** [Infactum/onec_dock#4]
скопировал содержимое скрипта в файл, добавил в начало инициализацию переменных export USERNAME=***
export PASSWORD=***
export VERSION=8.3.12.1595
, запустил на выполнение. Скрипт отрабатывает за пару секунд и выходит без сообщений. Попробовал убрать строчку "set -e", чтобы получить сообщения об ошибках, вывело следующее:
curl: (3) <url> malformed
curl: (3) <url> malformed

ОС: Ubuntu 16 Xenial

**Comment by Infactum** [comment]
Сначала убедитесь, что у вашей учетной записи есть доступ к нужным дистрибутивам.
Потом нужно исключить проблему наличия символов, требующих экранирования, в логине / пароле. Для этого выполните загрузку в интерактивном режиме `./onec_dock.sh -n`
Сам только что проверил - проблема не воспроизвелась. Значит изменений на стороне сайта с релизами нет.
